version: 2.1
orbs: 
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          command: |
            pip install requests
          name: Install Dependencies
      - run:
          command: |
            python -m unittest discover -s . -p 'MRTD.py' -v
          name: Run Tests
      - store_test_results:
          path: test-results
          
workflows:
  testing_finalProject:
    jobs:
      - build-and-test
