version: 2.1
orbs: 
    python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: 
          command: |
            pip install pytest
            pip install unittest
            python3 -m unittest discover -v
            pip install requests
            unittest --junitxml=test-results/junit.xml MTTDtest.py
      - store_test_results:
          path: test-results
          
workflows:
  testing_MTTD.py:
    jobs:
      - build-and-test 
